services:
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=${DB_USER:-hello_flask}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-hello_flask}
      - POSTGRES_DB=${DB_NAME:-ecommerce_prod}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-hello_flask} -d ${DB_NAME:-ecommerce_prod}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  web:
    build: .
    ports:
      - "5050:5000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql+psycopg://${DB_USER:-hello_flask}:${DB_PASSWORD:-hello_flask}@db:5432/${DB_NAME:-ecommerce_prod}
      - REDIS_URL=redis://redis:6379/0
      - FLASK_ENV=development
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: >
      sh -c "flask db upgrade && gunicorn  --bind 0.0.0.0:5000 'app:create_app()'"

volumes:
  postgres_data: